[general]
email = "aayushinagar385@gmail.com"
[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "fehfsdcnjsbdc.wndlnwEJBUE"
client_id = "463029658788-vhf7h3ul6kupohd1dik44htsc8jjumm8.apps.googleusercontent.com"
client_secret = "****s1qt"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"